import type { BackgroundStyle, BackgroundVariant, FontPairing, TemplateId } from "@/types";

export type TemplateCategory =
  | "Minimal"
  | "Corporate"
  | "Tech / Startup"
  | "Creative"
  | "Luxury"
  | "Dark Mode"
  | "Gradient"
  | "Glassmorphism"
  | "Editorial"
  | "Bold Typography";

export type TemplateLayout =
  | "split"
  | "stack"
  | "editorial"
  | "center"
  | "bold";

export interface CardTemplate {
  id: TemplateId;
  name: string;
  category: TemplateCategory;
  layout: TemplateLayout;
  font: FontPairing;
  iconStyle: "line" | "solid" | "minimal" | "bold";
  backgroundStyle: BackgroundStyle;
  backgroundVariant?: BackgroundVariant;
  spacing: number;
  padding: number;
  borderRadius: number;
  intensity: number;
}

export const TEMPLATES: CardTemplate[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // MINIMAL (10 templates) - Clean, whitespace-focused designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "whisper",
    name: "Whisper",
    category: "Minimal",
    layout: "split",
    font: "geist",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 12,
    padding: 32,
    borderRadius: 0,
    intensity: 8,
  },
  {
    id: "breath",
    name: "Breath",
    category: "Minimal",
    layout: "center",
    font: "inter",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 14,
    padding: 36,
    borderRadius: 4,
    intensity: 5,
  },
  {
    id: "mist",
    name: "Mist",
    category: "Minimal",
    layout: "stack",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 28,
    borderRadius: 8,
    intensity: 12,
  },
  {
    id: "silence",
    name: "Silence",
    category: "Minimal",
    layout: "editorial",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v3",
    spacing: 11,
    padding: 30,
    borderRadius: 2,
    intensity: 6,
  },
  {
    id: "void-white",
    name: "Void White",
    category: "Minimal",
    layout: "split",
    font: "jetbrains-mono",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 0,
    intensity: 10,
  },
  {
    id: "paper-thin",
    name: "Paper Thin",
    category: "Minimal",
    layout: "stack",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 13,
    padding: 34,
    borderRadius: 6,
    intensity: 4,
  },
  {
    id: "ghost",
    name: "Ghost",
    category: "Minimal",
    layout: "center",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 30,
    borderRadius: 12,
    intensity: 15,
  },
  {
    id: "blank-slate",
    name: "Blank Slate",
    category: "Minimal",
    layout: "editorial",
    font: "inter",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 28,
    borderRadius: 0,
    intensity: 3,
  },
  {
    id: "quiet",
    name: "Quiet",
    category: "Minimal",
    layout: "split",
    font: "geist",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v5",
    spacing: 11,
    padding: 32,
    borderRadius: 10,
    intensity: 18,
  },
  {
    id: "hush",
    name: "Hush",
    category: "Minimal",
    layout: "stack",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v3",
    spacing: 12,
    padding: 30,
    borderRadius: 4,
    intensity: 8,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORPORATE (10 templates) - Professional, trustworthy designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "boardroom",
    name: "Boardroom",
    category: "Corporate",
    layout: "split",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 8,
    intensity: 22,
  },
  {
    id: "handshake",
    name: "Handshake",
    category: "Corporate",
    layout: "editorial",
    font: "georgia",
    iconStyle: "solid",
    backgroundStyle: "geometric",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 28,
    borderRadius: 6,
    intensity: 35,
  },
  {
    id: "cornerstone",
    name: "Cornerstone",
    category: "Corporate",
    layout: "stack",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v3",
    spacing: 11,
    padding: 26,
    borderRadius: 10,
    intensity: 28,
  },
  {
    id: "summit",
    name: "Summit",
    category: "Corporate",
    layout: "center",
    font: "geist",
    iconStyle: "minimal",
    backgroundStyle: "geometric",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 30,
    borderRadius: 12,
    intensity: 40,
  },
  {
    id: "sterling",
    name: "Sterling",
    category: "Corporate",
    layout: "split",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v4",
    spacing: 10,
    padding: 28,
    borderRadius: 4,
    intensity: 20,
  },
  {
    id: "chairman",
    name: "Chairman",
    category: "Corporate",
    layout: "editorial",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "geometric",
    backgroundVariant: "v5",
    spacing: 12,
    padding: 32,
    borderRadius: 8,
    intensity: 45,
  },
  {
    id: "covenant",
    name: "Covenant",
    category: "Corporate",
    layout: "stack",
    font: "inter",
    iconStyle: "solid",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 26,
    borderRadius: 6,
    intensity: 25,
  },
  {
    id: "granite",
    name: "Granite",
    category: "Corporate",
    layout: "split",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v3",
    spacing: 11,
    padding: 28,
    borderRadius: 10,
    intensity: 38,
  },
  {
    id: "milestone",
    name: "Milestone",
    category: "Corporate",
    layout: "center",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 30,
    borderRadius: 8,
    intensity: 18,
  },
  {
    id: "benchmark",
    name: "Benchmark",
    category: "Corporate",
    layout: "editorial",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v4",
    spacing: 10,
    padding: 28,
    borderRadius: 12,
    intensity: 42,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TECH / STARTUP (10 templates) - Modern, innovative designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "launchpad",
    name: "Launchpad",
    category: "Tech / Startup",
    layout: "stack",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v1",
    spacing: 11,
    padding: 26,
    borderRadius: 16,
    intensity: 75,
  },
  {
    id: "hyperloop",
    name: "Hyperloop",
    category: "Tech / Startup",
    layout: "split",
    font: "jetbrains-mono",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v4",
    spacing: 10,
    padding: 24,
    borderRadius: 20,
    intensity: 85,
  },
  {
    id: "blockchain",
    name: "Blockchain",
    category: "Tech / Startup",
    layout: "center",
    font: "geist",
    iconStyle: "minimal",
    backgroundStyle: "geometric",
    backgroundVariant: "v2",
    spacing: 12,
    padding: 28,
    borderRadius: 18,
    intensity: 65,
  },
  {
    id: "satellite",
    name: "Satellite",
    category: "Tech / Startup",
    layout: "editorial",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "noise",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 14,
    intensity: 58,
  },
  {
    id: "terraform",
    name: "Terraform",
    category: "Tech / Startup",
    layout: "stack",
    font: "jetbrains-mono",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v3",
    spacing: 11,
    padding: 24,
    borderRadius: 12,
    intensity: 72,
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "Tech / Startup",
    layout: "bold",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "geometric",
    backgroundVariant: "v5",
    spacing: 12,
    padding: 28,
    borderRadius: 22,
    intensity: 80,
  },
  {
    id: "webhook",
    name: "Webhook",
    category: "Tech / Startup",
    layout: "split",
    font: "jetbrains-mono",
    iconStyle: "minimal",
    backgroundStyle: "noise",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 26,
    borderRadius: 16,
    intensity: 62,
  },
  {
    id: "serverless",
    name: "Serverless",
    category: "Tech / Startup",
    layout: "center",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v6",
    spacing: 11,
    padding: 28,
    borderRadius: 18,
    intensity: 78,
  },
  {
    id: "algorithm",
    name: "Algorithm",
    category: "Tech / Startup",
    layout: "editorial",
    font: "jetbrains-mono",
    iconStyle: "bold",
    backgroundStyle: "geometric",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 24,
    borderRadius: 14,
    intensity: 68,
  },
  {
    id: "datastream",
    name: "Datastream",
    category: "Tech / Startup",
    layout: "stack",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "noise",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 26,
    borderRadius: 20,
    intensity: 70,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CREATIVE (10 templates) - Artistic, expressive designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "brushstroke",
    name: "Brushstroke",
    category: "Creative",
    layout: "split",
    font: "playfair",
    iconStyle: "bold",
    backgroundStyle: "abstract",
    backgroundVariant: "v1",
    spacing: 12,
    padding: 28,
    borderRadius: 24,
    intensity: 82,
  },
  {
    id: "collage",
    name: "Collage",
    category: "Creative",
    layout: "bold",
    font: "geist",
    iconStyle: "solid",
    backgroundStyle: "abstract",
    backgroundVariant: "v4",
    spacing: 14,
    padding: 30,
    borderRadius: 28,
    intensity: 90,
  },
  {
    id: "origami",
    name: "Origami",
    category: "Creative",
    layout: "center",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v2",
    spacing: 11,
    padding: 26,
    borderRadius: 16,
    intensity: 70,
  },
  {
    id: "kaleidoscope",
    name: "Kaleidoscope",
    category: "Creative",
    layout: "stack",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "abstract",
    backgroundVariant: "v5",
    spacing: 12,
    padding: 28,
    borderRadius: 22,
    intensity: 95,
  },
  {
    id: "watercolor",
    name: "Watercolor",
    category: "Creative",
    layout: "editorial",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "abstract",
    backgroundVariant: "v3",
    spacing: 10,
    padding: 30,
    borderRadius: 18,
    intensity: 75,
  },
  {
    id: "mosaic",
    name: "Mosaic",
    category: "Creative",
    layout: "split",
    font: "inter",
    iconStyle: "solid",
    backgroundStyle: "geometric",
    backgroundVariant: "v6",
    spacing: 11,
    padding: 26,
    borderRadius: 20,
    intensity: 78,
  },
  {
    id: "graffiti",
    name: "Graffiti",
    category: "Creative",
    layout: "bold",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "abstract",
    backgroundVariant: "v1",
    spacing: 14,
    padding: 28,
    borderRadius: 26,
    intensity: 92,
  },
  {
    id: "sculpture",
    name: "Sculpture",
    category: "Creative",
    layout: "center",
    font: "playfair",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v4",
    spacing: 10,
    padding: 32,
    borderRadius: 14,
    intensity: 65,
  },
  {
    id: "gallery",
    name: "Gallery",
    category: "Creative",
    layout: "editorial",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 12,
    padding: 30,
    borderRadius: 10,
    intensity: 25,
  },
  {
    id: "atelier",
    name: "Atelier",
    category: "Creative",
    layout: "stack",
    font: "playfair",
    iconStyle: "line",
    backgroundStyle: "abstract",
    backgroundVariant: "v2",
    spacing: 11,
    padding: 28,
    borderRadius: 20,
    intensity: 72,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LUXURY (10 templates) - Premium, sophisticated designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "champagne",
    name: "Champagne",
    category: "Luxury",
    layout: "editorial",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 11,
    padding: 32,
    borderRadius: 4,
    intensity: 15,
  },
  {
    id: "caviar",
    name: "Caviar",
    category: "Luxury",
    layout: "center",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v5",
    spacing: 12,
    padding: 34,
    borderRadius: 0,
    intensity: 22,
  },
  {
    id: "cashmere",
    name: "Cashmere",
    category: "Luxury",
    layout: "split",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "noise",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 30,
    borderRadius: 8,
    intensity: 28,
  },
  {
    id: "mahogany",
    name: "Mahogany",
    category: "Luxury",
    layout: "stack",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v4",
    spacing: 11,
    padding: 32,
    borderRadius: 6,
    intensity: 20,
  },
  {
    id: "venetian",
    name: "Venetian",
    category: "Luxury",
    layout: "editorial",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v3",
    spacing: 10,
    padding: 30,
    borderRadius: 10,
    intensity: 35,
  },
  {
    id: "versailles",
    name: "Versailles",
    category: "Luxury",
    layout: "center",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "geometric",
    backgroundVariant: "v1",
    spacing: 12,
    padding: 34,
    borderRadius: 12,
    intensity: 42,
  },
  {
    id: "monaco",
    name: "Monaco",
    category: "Luxury",
    layout: "split",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 28,
    borderRadius: 8,
    intensity: 18,
  },
  {
    id: "dynasty",
    name: "Dynasty",
    category: "Luxury",
    layout: "editorial",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "geometric",
    backgroundVariant: "v5",
    spacing: 11,
    padding: 32,
    borderRadius: 4,
    intensity: 38,
  },
  {
    id: "heritage",
    name: "Heritage",
    category: "Luxury",
    layout: "stack",
    font: "playfair",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v3",
    spacing: 10,
    padding: 30,
    borderRadius: 6,
    intensity: 24,
  },
  {
    id: "sovereign",
    name: "Sovereign",
    category: "Luxury",
    layout: "center",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "noise",
    backgroundVariant: "v2",
    spacing: 12,
    padding: 34,
    borderRadius: 10,
    intensity: 32,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DARK MODE (10 templates) - Elegant dark designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "obsidian",
    name: "Obsidian",
    category: "Dark Mode",
    layout: "split",
    font: "geist",
    iconStyle: "minimal",
    backgroundStyle: "noise",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 14,
    intensity: 52,
  },
  {
    id: "charcoal",
    name: "Charcoal",
    category: "Dark Mode",
    layout: "stack",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v5",
    spacing: 11,
    padding: 28,
    borderRadius: 12,
    intensity: 45,
  },
  {
    id: "raven",
    name: "Raven",
    category: "Dark Mode",
    layout: "editorial",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "noise",
    backgroundVariant: "v3",
    spacing: 10,
    padding: 30,
    borderRadius: 8,
    intensity: 58,
  },
  {
    id: "onyx-night",
    name: "Onyx Night",
    category: "Dark Mode",
    layout: "center",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 32,
    borderRadius: 10,
    intensity: 40,
  },
  {
    id: "phantom",
    name: "Phantom",
    category: "Dark Mode",
    layout: "bold",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v2",
    spacing: 12,
    padding: 26,
    borderRadius: 18,
    intensity: 72,
  },
  {
    id: "umbra",
    name: "Umbra",
    category: "Dark Mode",
    layout: "split",
    font: "jetbrains-mono",
    iconStyle: "minimal",
    backgroundStyle: "noise",
    backgroundVariant: "v4",
    spacing: 10,
    padding: 24,
    borderRadius: 16,
    intensity: 62,
  },
  {
    id: "blackout",
    name: "Blackout",
    category: "Dark Mode",
    layout: "stack",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "solid",
    backgroundVariant: "v5",
    spacing: 11,
    padding: 28,
    borderRadius: 14,
    intensity: 48,
  },
  {
    id: "shadows",
    name: "Shadows",
    category: "Dark Mode",
    layout: "editorial",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "noise",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 12,
    intensity: 55,
  },
  {
    id: "abyss",
    name: "Abyss",
    category: "Dark Mode",
    layout: "center",
    font: "jetbrains-mono",
    iconStyle: "minimal",
    backgroundStyle: "gradient",
    backgroundVariant: "v6",
    spacing: 12,
    padding: 30,
    borderRadius: 20,
    intensity: 78,
  },
  {
    id: "eclipse-dark",
    name: "Eclipse",
    category: "Dark Mode",
    layout: "bold",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "noise",
    backgroundVariant: "v2",
    spacing: 12,
    padding: 28,
    borderRadius: 16,
    intensity: 68,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GRADIENT (10 templates) - Vibrant, flowing designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "sunrise",
    name: "Sunrise",
    category: "Gradient",
    layout: "center",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v1",
    spacing: 11,
    padding: 28,
    borderRadius: 18,
    intensity: 82,
  },
  {
    id: "nebula",
    name: "Nebula",
    category: "Gradient",
    layout: "stack",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 26,
    borderRadius: 22,
    intensity: 92,
  },
  {
    id: "prism",
    name: "Prism",
    category: "Gradient",
    layout: "split",
    font: "inter",
    iconStyle: "minimal",
    backgroundStyle: "gradient",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 28,
    borderRadius: 16,
    intensity: 78,
  },
  {
    id: "borealis",
    name: "Borealis",
    category: "Gradient",
    layout: "editorial",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v5",
    spacing: 11,
    padding: 30,
    borderRadius: 20,
    intensity: 88,
  },
  {
    id: "spectrum",
    name: "Spectrum",
    category: "Gradient",
    layout: "bold",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v3",
    spacing: 14,
    padding: 28,
    borderRadius: 24,
    intensity: 95,
  },
  {
    id: "chromatic",
    name: "Chromatic",
    category: "Gradient",
    layout: "center",
    font: "geist",
    iconStyle: "solid",
    backgroundStyle: "gradient",
    backgroundVariant: "v6",
    spacing: 11,
    padding: 26,
    borderRadius: 18,
    intensity: 85,
  },
  {
    id: "iridescent",
    name: "Iridescent",
    category: "Gradient",
    layout: "stack",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 28,
    borderRadius: 20,
    intensity: 80,
  },
  {
    id: "holograph",
    name: "Holograph",
    category: "Gradient",
    layout: "split",
    font: "jetbrains-mono",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 26,
    borderRadius: 22,
    intensity: 90,
  },
  {
    id: "dreamscape",
    name: "Dreamscape",
    category: "Gradient",
    layout: "editorial",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "gradient",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 30,
    borderRadius: 16,
    intensity: 75,
  },
  {
    id: "mirage",
    name: "Mirage",
    category: "Gradient",
    layout: "center",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "gradient",
    backgroundVariant: "v5",
    spacing: 11,
    padding: 28,
    borderRadius: 18,
    intensity: 83,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GLASSMORPHISM (10 templates) - Frosted, translucent designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "frosted",
    name: "Frosted",
    category: "Glassmorphism",
    layout: "split",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "glass",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 20,
    intensity: 65,
  },
  {
    id: "crystal-clear",
    name: "Crystal Clear",
    category: "Glassmorphism",
    layout: "center",
    font: "inter",
    iconStyle: "minimal",
    backgroundStyle: "glass",
    backgroundVariant: "v2",
    spacing: 11,
    padding: 28,
    borderRadius: 24,
    intensity: 58,
  },
  {
    id: "dewdrop",
    name: "Dewdrop",
    category: "Glassmorphism",
    layout: "stack",
    font: "geist",
    iconStyle: "line",
    backgroundStyle: "glass",
    backgroundVariant: "v3",
    spacing: 10,
    padding: 26,
    borderRadius: 18,
    intensity: 62,
  },
  {
    id: "glacier",
    name: "Glacier",
    category: "Glassmorphism",
    layout: "editorial",
    font: "inter",
    iconStyle: "minimal",
    backgroundStyle: "glass",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 30,
    borderRadius: 22,
    intensity: 70,
  },
  {
    id: "icesheet",
    name: "Ice Sheet",
    category: "Glassmorphism",
    layout: "bold",
    font: "geist",
    iconStyle: "bold",
    backgroundStyle: "glass",
    backgroundVariant: "v5",
    spacing: 12,
    padding: 28,
    borderRadius: 26,
    intensity: 75,
  },
  {
    id: "translucent",
    name: "Translucent",
    category: "Glassmorphism",
    layout: "split",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "glass",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 26,
    borderRadius: 20,
    intensity: 55,
  },
  {
    id: "haze",
    name: "Haze",
    category: "Glassmorphism",
    layout: "center",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "glass",
    backgroundVariant: "v6",
    spacing: 11,
    padding: 30,
    borderRadius: 22,
    intensity: 68,
  },
  {
    id: "blur-glass",
    name: "Blur Glass",
    category: "Glassmorphism",
    layout: "stack",
    font: "geist",
    iconStyle: "solid",
    backgroundStyle: "glass",
    backgroundVariant: "v2",
    spacing: 10,
    padding: 26,
    borderRadius: 18,
    intensity: 72,
  },
  {
    id: "window",
    name: "Window",
    category: "Glassmorphism",
    layout: "editorial",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "glass",
    backgroundVariant: "v3",
    spacing: 12,
    padding: 28,
    borderRadius: 16,
    intensity: 60,
  },
  {
    id: "lucid",
    name: "Lucid",
    category: "Glassmorphism",
    layout: "split",
    font: "geist",
    iconStyle: "minimal",
    backgroundStyle: "glass",
    backgroundVariant: "v4",
    spacing: 11,
    padding: 28,
    borderRadius: 24,
    intensity: 64,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EDITORIAL (10 templates) - Magazine, publication designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "headline",
    name: "Headline",
    category: "Editorial",
    layout: "editorial",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 30,
    borderRadius: 8,
    intensity: 18,
  },
  {
    id: "byline",
    name: "Byline",
    category: "Editorial",
    layout: "split",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 11,
    padding: 28,
    borderRadius: 6,
    intensity: 22,
  },
  {
    id: "frontpage",
    name: "Front Page",
    category: "Editorial",
    layout: "stack",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "geometric",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 30,
    borderRadius: 10,
    intensity: 35,
  },
  {
    id: "manuscript",
    name: "Manuscript",
    category: "Editorial",
    layout: "editorial",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v3",
    spacing: 12,
    padding: 32,
    borderRadius: 4,
    intensity: 15,
  },
  {
    id: "gazette",
    name: "Gazette",
    category: "Editorial",
    layout: "center",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v4",
    spacing: 10,
    padding: 28,
    borderRadius: 12,
    intensity: 25,
  },
  {
    id: "chronicle",
    name: "Chronicle",
    category: "Editorial",
    layout: "split",
    font: "georgia",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v2",
    spacing: 11,
    padding: 30,
    borderRadius: 8,
    intensity: 38,
  },
  {
    id: "tribune",
    name: "Tribune",
    category: "Editorial",
    layout: "editorial",
    font: "playfair",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v5",
    spacing: 10,
    padding: 28,
    borderRadius: 6,
    intensity: 20,
  },
  {
    id: "dispatch",
    name: "Dispatch",
    category: "Editorial",
    layout: "stack",
    font: "inter",
    iconStyle: "line",
    backgroundStyle: "geometric",
    backgroundVariant: "v3",
    spacing: 12,
    padding: 30,
    borderRadius: 10,
    intensity: 42,
  },
  {
    id: "periodical",
    name: "Periodical",
    category: "Editorial",
    layout: "center",
    font: "georgia",
    iconStyle: "minimal",
    backgroundStyle: "solid",
    backgroundVariant: "v1",
    spacing: 10,
    padding: 32,
    borderRadius: 8,
    intensity: 16,
  },
  {
    id: "journal",
    name: "Journal",
    category: "Editorial",
    layout: "editorial",
    font: "playfair",
    iconStyle: "line",
    backgroundStyle: "solid",
    backgroundVariant: "v2",
    spacing: 11,
    padding: 30,
    borderRadius: 4,
    intensity: 24,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BOLD TYPOGRAPHY (10 templates) - Strong, impactful designs
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "shout",
    name: "Shout",
    category: "Bold Typography",
    layout: "bold",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "geometric",
    backgroundVariant: "v1",
    spacing: 14,
    padding: 28,
    borderRadius: 18,
    intensity: 78,
  },
  {
    id: "thunder",
    name: "Thunder",
    category: "Bold Typography",
    layout: "stack",
    font: "geist",
    iconStyle: "solid",
    backgroundStyle: "abstract",
    backgroundVariant: "v4",
    spacing: 12,
    padding: 30,
    borderRadius: 22,
    intensity: 88,
  },
  {
    id: "impact",
    name: "Impact",
    category: "Bold Typography",
    layout: "center",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v2",
    spacing: 14,
    padding: 28,
    borderRadius: 20,
    intensity: 85,
  },
  {
    id: "brutalist",
    name: "Brutalist",
    category: "Bold Typography",
    layout: "bold",
    font: "jetbrains-mono",
    iconStyle: "bold",
    backgroundStyle: "solid",
    backgroundVariant: "v5",
    spacing: 12,
    padding: 26,
    borderRadius: 0,
    intensity: 65,
  },
  {
    id: "billboard",
    name: "Billboard",
    category: "Bold Typography",
    layout: "split",
    font: "geist",
    iconStyle: "solid",
    backgroundStyle: "abstract",
    backgroundVariant: "v1",
    spacing: 14,
    padding: 30,
    borderRadius: 24,
    intensity: 92,
  },
  {
    id: "monument",
    name: "Monument",
    category: "Bold Typography",
    layout: "center",
    font: "playfair",
    iconStyle: "bold",
    backgroundStyle: "geometric",
    backgroundVariant: "v3",
    spacing: 12,
    padding: 32,
    borderRadius: 16,
    intensity: 75,
  },
  {
    id: "colossus",
    name: "Colossus",
    category: "Bold Typography",
    layout: "bold",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "gradient",
    backgroundVariant: "v5",
    spacing: 16,
    padding: 30,
    borderRadius: 26,
    intensity: 95,
  },
  {
    id: "titan",
    name: "Titan",
    category: "Bold Typography",
    layout: "stack",
    font: "geist",
    iconStyle: "solid",
    backgroundStyle: "abstract",
    backgroundVariant: "v2",
    spacing: 14,
    padding: 28,
    borderRadius: 22,
    intensity: 90,
  },
  {
    id: "mammoth",
    name: "Mammoth",
    category: "Bold Typography",
    layout: "split",
    font: "playfair",
    iconStyle: "bold",
    backgroundStyle: "geometric",
    backgroundVariant: "v6",
    spacing: 12,
    padding: 30,
    borderRadius: 20,
    intensity: 82,
  },
  {
    id: "earthquake",
    name: "Earthquake",
    category: "Bold Typography",
    layout: "bold",
    font: "inter",
    iconStyle: "bold",
    backgroundStyle: "abstract",
    backgroundVariant: "v4",
    spacing: 16,
    padding: 28,
    borderRadius: 28,
    intensity: 98,
  },
];

export function getTemplateById(id: TemplateId) {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  "Minimal",
  "Corporate",
  "Tech / Startup",
  "Creative",
  "Luxury",
  "Dark Mode",
  "Gradient",
  "Glassmorphism",
  "Editorial",
  "Bold Typography",
];
